#!/bin/bash
#set -e
##################################################################################################################
# Author  :  anisbsalah
# Github  :  https://github.com/anisbsalah
##################################################################################################################
#
# DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
# CURRENT_DIR="$(pwd)"
##################################################################################################################

#[chaotic-aur]
#SigLevel = Required DatabaseOptional
#Include = /etc/pacman.d/chaotic-mirrorlist

# Set the file path
FILE="/etc/pacman.conf"

# Search for "chaotic-aur" in the specified file
if ! grep -q "chaotic-aur" "${FILE}"; then

	echo
	tput setaf 3
	echo "######################################################################################################"
	echo "Adding chaotic-aur repository to ${FILE}"
	echo "######################################################################################################"
	tput sgr0

	# Append the configuration for chaotic-aur to the file
	{
		echo ""
		echo "#[chaotic-aur]"
		echo "#SigLevel = Required DatabaseOptional"
		echo "#Include = /etc/pacman.d/chaotic-mirrorlist"
	} | sudo tee -a "${FILE}"
fi

if grep -q "#\[chaotic-aur\]" /etc/pacman.conf; then
	echo "########################################"
	echo "Activate the chaotic repo"
	echo "########################################"
	sudo sed -i "s/#\[chaotic-aur\]/\[chaotic-aur\]/g" /etc/pacman.conf
	sudo sed -i "s/#SigLevel = Required DatabaseOptional/SigLevel = Required DatabaseOptional/g" /etc/pacman.conf
	sudo sed -i "s/#Include = \/etc\/pacman.d\/chaotic-mirrorlist/Include = \/etc\/pacman.d\/chaotic-mirrorlist/g" /etc/pacman.conf
else
	echo "########################################"
	echo "Deactivate the chaotic repo"
	echo "########################################"
	sudo sed -i '0,/\[chaotic-aur\]/s/\[chaotic-aur\]/#\[chaotic-aur\]/' /etc/pacman.conf
	sudo sed -i '/chaotic-aur/{n;s/^SigLevel = Required DatabaseOptional/#SigLevel = Required DatabaseOptional/;}' /etc/pacman.conf
	sudo sed -i '0,/Include = \/etc\/pacman.d\/chaotic-mirrorlist/s/Include = \/etc\/pacman.d\/chaotic-mirrorlist/#Include = \/etc\/pacman.d\/chaotic-mirrorlist/' /etc/pacman.conf
fi

echo
tput setaf 3
echo "######################################################################################################"
echo "Updating database..."
echo "######################################################################################################"
tput sgr0
echo

sudo pacman -Sy

echo
echo "######################################################################################################"
echo "###                                DONE - YOU CAN CLOSE THIS WINDOW                                ###"
echo "######################################################################################################"
echo
